CC=gcc
CFLAGS=-fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow
# LFLAGS=-lm

# require that an argument be provided at the command line for the target name

# compile: main.c
# 	$(CC) $(CFLAGS) main.c

compile:
	$(CC) $(CFLAGS) -o $() $().c $(LFLAGS)
